swagger: '2.0'
basePath: /
paths:
  '/marketinsights/predict/{model_id}/{training_id}':
    parameters:
      - name: model_id
        in: path
        required: true
        type: string
      - name: training_id
        in: path
        required: true
        type: string
    post:
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Provide the features dataset:'
      operationId: post_model
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            $ref: '#/definitions/Provide the features dataset:'
      tags:
        - marketinsights
info:
  title: MarketInsights Model API
  version: '1.0'
  x-ibm-name: marketinsights-model-api
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: default
    description: Default namespace
  - name: marketinsights
    description: 'Train, Deploy, and Score models via the MarketInsights API'
definitions:
  'Provide the features dataset:':
    properties:
      market:
        type: string
      data:
        type: array
        items:
          type: array
          items:
            type: number
      tz:
        type: string
      index:
        type: array
        items:
          type: string
    type: object
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: 'https://app2.marketinsightsonline.com$(request.path)'
          tls-profile: $(invoke-tls-profile)
    catch: []
  properties:
    invoke-tls-profile:
      value: ''
      description: ''
      encoded: false
  catalogs:
    api:
      properties:
        invoke-tls-profile: mioclientserverprofile
host: $(catalog.host)
schemes:
  - https
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
